version: '3.8'

services:
  company-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BRAVE_SEARCH_API_KEY=${BRAVE_SEARCH_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - LLM_MODEL=${LLM_MODEL:-gpt-4o-mini}
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped 